#run shell script file in yaml file in Windows Slef hosted runner
name: 'Run shell script in Windows Self hosted runner'
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Run shell script
      run: |
        ./test.sh
