#run hello world   in yaml file then store into test.txt file push rto remote in Windows Slef hosted runner
name: 'Hello World'
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Run a one-line script
      run: |
          .\test.py > test.txt
    - name: Commit files
      run: |
        git config --local user.email "charanv@devtools.in"
        git config --local user.name "Charan-SV"
        git add .
        git commit -m "Add test.txt"
    - name: Push changes
      run: git push


