# In the manual triger happen , python.py will be excuted it checkout from repository
# and run the python.py file in self-hosted runner windows machine
name: Python
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Run python.py
      run: |
        python python.py
