on:
  push:
     branches: main

jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Run test.sh
      - run: |
            shell: bash
            working-directory: ./test.sh
