on:
  workflow_dispatch

jobs:
  job1:
    name: test
    runs-on: [self-hosted, windows]
    steps:
      - name: Run test.sh
      - run: |
            shell: bash
            working-directory: ./test.sh
