on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted,windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run test.sh
        run: |
          chmod +x ./test.sh
          ./test.sh




            
