on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted,windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run test.sh
        run: 
          ./test.sh




            
