# In the manual triger happen , python.py will be excuted it checkout from repository
# and run the python.py file in self-hosted runner windows machine
name: Python
on: [workflow_dispatch]
jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run python.py
      run: |
        python python.py
