name: Python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the version of Python you want to install
        shell: powershell # Use PowerShell instead of the default shell
      
      - name: Run python.py
        run: |
          python python.py
