name: List Repositories

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository list
        id: repo-list
        run: |
          repositories=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/orgs/{ORG}/members?per_page=100")
          echo "Repositories in {ORG}:"
          echo "$repositories"
