on: push

name: My Workflow

jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Jira Creation Demo
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://trainingproject1.atlassian.net/
          JIRA_API_TOKEN: ${{ secrets.PAT }}
          JIRA_ISSUE_DESCRIPTION: Demo'ing Jira Issue Creation
          JIRA_ISSUE_SUMMARY: Demo'ing Jira Issue Creation
          JIRA_ISSUE_TYPE: Bug
          JIRA_PROJECT: GI
          JIRA_USERNAME: charanv@devtools.in
