name: List Repositories

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository list
        id: repo-list
        run: |
          repositories=$(curl -L -H "Accept: application/vnd.github+json" / "Authorization: Bearer ${{ secrets.PAT }}" \ "X-GitHub-Api-Version: 2022-11-28" \ https://api.github.com/orgs/{ORG}/members)
          echo "$repositories"
