name: List Repositories

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository list
        id: repo-list
        run: |
          repositories=$(curl -H "Authorization: token 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" https://api.github.com/orgs/CGO-22/repos | grep -o '"name": "[^"]*"')
          echo "$repositories"
