name: List Repositories

on:
  workflow_dispatch:
  
env: 
   ORG : ${{ ORG }}

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository list
        id: repo-list
        run: |
          repositories=$(curl -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/orgs/$ORG/repos | grep -o '"name": "[^"]*"')
          echo "$repositories"
