name: List Repositories

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository list
        id: repo-list
        run: |
          repositories=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/orgs/{ORG}/repos?per_page=100&page=1" | \
            jq -r '.[].name')
          echo "Repositories in {organization}:"
          echo "$repositories"
