on: push

name: Test Create Issue

jobs:
  test-create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Chekouting repo
      uses: atlassian/gajira-login@v3
      
    - run: yarn install
    - run: yarn test

      
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    
    - name: Create
      id: create

      uses: ./
    
      
    
      with:
        project: GI
        issuetype: Task
        summary: Do the thing for ${{ github.repository }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
